export const arr = [{
    id: "1",
    carName: "Toyota",
    img: "./images/toyota-carrol.png",
    disciption: "The Toyota Corolla is a reliable, fuel-efficient compact sedan with a modern design and advanced safety features, and it is available with a diesel , electric engine option.",
    cost: 30000,
    btn: "Buy Now",
    edit: "Edit Now",
    speed: "Speed: 180km/h",
},
{
    id: "2",
    carName: "Toyota",
    img: "./images/toyota-corrola.png",
    disciption: "The Toyota Corolla is a reliable, fuel-efficient compact sedan with a modern design and advanced safety features, and it is available with an electric engine option.",
    cost: 35000,
    btn: "Buy Now",
    edit: "Edit Now",
    speed: "Speed: 180km/h",
},
{
    id: "3",
    carName: "Toyota",
    img: "./images/toyota.png",
    disciption: "The Toyota Corolla is a reliable, fuel-efficient compact sedan with a modern design and advanced safety features, and it is available with a diesel engine option.",
    cost: 40000,
    btn: "Buy Now",
    edit: "Edit Now",
    speed: "Speed: 180km/h",
},
{
    id: "4",
    carName: "Tesla",
    img: "./images/tesla3.png",
    disciption: "The Tesla Model 3 is a stylish electric car with advanced tech, and it is available with an electric engine option, and it is available with a Electricity engine option.",
    cost: 50000,
    btn: "Buy Now",
    edit: "Edit Now",
    speed: "Speed: 225km/h",
},
{
    id: "5",
    carName: "Tesla",
    img: "./images/tesla4.png",
    disciption: "The Tesla Model 3 is a stylish electric car with advanced tech, and it is available with an electric engine option.",
    cost: 44000,
    btn: "Buy Now",
    edit: "Edit Now",
    speed: "Speed: 225km/h",
},
{
    id: "6",
    carName: "Tesla",
    img: "./images/tesla2.png",
    disciption: "The Tesla Model 3 is a stylish electric car with advanced tech, and it is available with an electric engine option.",
    cost: 40000,
    btn: "Buy Now",
    edit: "Edit Now",
    speed: "Speed: 225km/h",
},
{
    id: "7",
    carName: "Tesla",
    img: "./images/tesla1.png",
    disciption: "The Tesla Model 3 is a stylish electric car with advanced tech, and it is available with an electric engine option.",
    cost: 35000,
    btn: "Buy Now",
    edit: "Edit Now",
    speed: "Speed: 2225km/h",
},
{
    id: "8",
    carName: "BMW",
    img: "./images/bmw5.png",
    disciption: "The Tesla Model 3 is a stylish electric car with advanced tech, and it is available with a gasoline and diesel engine option.",
    cost: 50000,
    btn: "Buy Now",
    edit: "Edit Now",
    speed: "Speed: 2225km/h",
},
{
    id: "9",
    carName: "BMW",
    img: "./images/bmw2.webp",
    disciption: "The Tesla Model 3 is a stylish electric car with advanced tech, and it is available with a gasoline and electric engine option.",
    cost: 60000,
    btn: "Buy Now",
    edit: "Edit Now",
    speed: "Speed: 2225km/h",
},
{
    id: "10",
    carName: "BMW",
    img: "./images/bmw3.png",
    disciption: "The Tesla Model 3 is a stylish electric car with advanced tech, and it is available with a diesel engine option.",
    cost: 55000,
    btn: "Buy Now",
    edit: "Edit Now",
    speed: "Speed: 2225km/h",
},
{
    id: "11",
    carName: "BMW",
    img: "./images/bmw4.png",
    disciption: "The Tesla Model 3 is a stylish electric car with advanced tech, and it is available with a gasoline , diesel and electric engine option.",
    cost: 70000,
    btn: "Buy Now",
    edit: "Edit Now",
    speed: "Speed: 2225km/h",
},
{
    id: "12",
    carName: "Jeep",
    img: "./images/jeep1.png",
    disciption: "The Mercedes-Benz G-Class (G-Wagon) is a luxury SUV known for its boxy design and strong off-road performance, and it is available with a gasoline , diesel and electric engine option.",
    cost: 150000,
    btn: "Buy Now",
    edit: "Edit Now",
    speed: "Speed: 220 km/h",
},
{
    id: "13",
    carName: "Jeep",
    img: "./images/jeep2.png",
    disciption: "The Range Rover is a luxury SUV from Land Rover known for its elegant design, upscale interior, and strong off-road capabilities. It offers excellent performance and superior driving comfort, and it is available with a gasoline , diesel and electric engine option.",
    cost: 110000,
    btn: "Buy Now",
    edit: "Edit Now",
    speed: "Speed: 200 km/h",
},
{
    id: "14",
    carName: "Jeep",
    img: "./images/jeep3.png",
    disciption: "The Jeep is a rugged SUV with strong off-road abilities and a durable design, perfect for adventure and city driving, and it is available with a gasoline  and electric engine option.",
    cost: 80000,
    btn: "Buy Now",
    edit: "Edit Now",
    speed: "Speed: 125km/h",
},
{
    id: "15",
    carName: "Jeep",
    img: "./images/jeep4.png",
    disciption: "The Jeep is a rugged SUV with strong off-road abilities and a durable design, perfect for adventure and city driving, and it is available with a gasoline , diesel  engine option.",
    cost: 40000,
    btn: "Buy Now",
    edit: "Edit Now",
    speed: "Speed: 140km/h",
},
];
